services:
  api:
    container_name: map-app-api-dev
    build:
      dockerfile: ./api.Dockerfile
    depends_on:
      - db
    networks:
      - backend
      - db
    ports:
      - 8081:8081
    env_file: .env
    environment:
      - API_HOST=${API_HOST}
      - API_PORT=${API_PORT}
      - DATABASE=${DATABASE}
      - DATABASE_DIALECT=${DATABASE_DIALECT}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - ORS_API_KEY=${ORS_API_KEY}
      - FUEL_API_KEY=${FUEL_API_KEY}
      - MAPS_API_KEY=${MAPS_API_KEY}
      - GEOAPIFY_API_KEY=${GEOAPIFY_API_KEY}
    volumes:
      - type: bind
        source: ./server
        target: /app/server
    command: npm run dev

  db:
    container_name: map-app-db-dev
    image: mariadb:11.3.2
    networks:
      - db
    ports:
      - 3306:3306
    env_file: .env
    environment:
      - MARIADB_ROOT_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_DATABASE=${DATABASE}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - map-app-db:/var/lib/mysql

  adminer:
    build:
      dockerfile: adminer.Dockerfile
    networks:
      - db
    ports:
      - 8080:8080

networks:
  backend:
    name: map-app-backend-dev
  db:
    name: map-app-db-dev

volumes:
  map-app-db: